### ISSUE TITLE
Parsed output missing IGK and IGL entries in the locus column after IgBlast annotation

### ISSUE THREAD

**Issue by liu1441452945** [MathildeFogPerez/manuscript-bnab-foglierini#1]
Dear Author,

Thank you very much for developing this tool. I greatly appreciate your work. While using it, I noticed that in the parsed output file, the locus column only contains IGH, with no entries for IGK or IGL. I suspect this might be due to an issue with my IgBlast reference sequence download, as I only downloaded the V, D, J references for IGH and did not include the light chain (IGK and IGL) references.

In the cellranger_out_to_changeO.sh script, I noticed that only three reference files are used. I would like to confirm whether these files already contain all the necessary information for both heavy chain (IGH) and light chains (IGK and IGL), or if I need to separately download all the V, D, J references for both heavy and light chains.

Thank you very much for your time and help!

**Comment by MathildeFogPerez** [comment]
Hello!

yes in the three reference files you have to include the light chain ( VK/VL and JK/JL).
best

Mathilde

**Comment by liu1441452945** [comment]
Dear Mathilde,
Thank you very much for your response! I have successfully completed the run, and your assistance was greatly helpful.
Liu
